Repository beefproject/beef, pull requests merged in 2020-01, with the labels that each got.

#1845 Fix broken admin ui access
  config.yaml
  core/bootstrap.rb
  core/main/router/error_responses.rb
  core/main/router/router.rb
  extensions/admin_ui/classes/httpcontroller.rb
  extensions/admin_ui/controllers/authentication/authentication.rb
  spec/beef/extensions/adminui_spec.rb
Labels: Admin UI, Defect, Priority Critical

#1853 Add error handling and minor code cleanup
  core/main/network_stack/assethandler.rb
Labels: Enhancement

#1860 Add Ruby 2.7.0 to travis.yml
  .travis.yml
Labels: Test

#1861 Use OID-style key/value data for BrowserDetails network details
  core/main/handlers/browserdetails.rb
Labels: Enhancement

#1863 update the destroy to destroy all
  core/main/rest/handlers/hookedbrowsers.rb
  spec/beef/core/main/handlers/browser_details_handler_spec.rb
Labels: Defect
