Repository beefproject/beef, pull requests merged in 2021-11, with the labels that each got.

#2218 MAINTAINABILITY: Added approval before code execution.
  .github/workflows/github_actions.yml
Labels: Test, Maintainability, Update

#2199 Enhancement - Check for update on launch
  beef
Labels: Enhancement

#2205 Modules: Add apache_tomcat_examples_cookie_disclosure module
  modules/browser/hooked_domain/apache_tomcat_examples_cookie_disclosure/command.js
  modules/browser/hooked_domain/apache_tomcat_examples_cookie_disclosure/config.yaml
  modules/browser/hooked_domain/apache_tomcat_examples_cookie_disclosure/module.rb
Labels: Module

#2224 Travis cleanup
  .travis.yml
Labels: Maintainability
